apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wui5nduhk-python 
  janus-idp.io/tekton: wui5nduhk-python
  backstage.io/kubernetes-id: wui5nduhk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wui5nduhk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml